# Generated by Django 5.0.1 on 2024-04-16 19:10

import django.core.validators
import django.db.models.deletion
import petapp.models
import phonenumber_field.modelfields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'Типы животных',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('patronymic', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('photo_avatar', models.ImageField(blank=True, null=True, upload_to='customer/', verbose_name='Фото пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('shipping_address', models.TextField(verbose_name='Адрес доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, verbose_name='Номер заказа')),
                ('payment_id', models.CharField(blank=True, max_length=128, verbose_name='Идентификатор платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлённая дата ')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='created', max_length=20, verbose_name='Статус')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.basket', verbose_name='Корзина')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='petapp.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='Название продукта')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('origin_country', models.CharField(max_length=100, verbose_name='Страна производитель')),
                ('photo_product', models.ImageField(upload_to='products/', validators=[petapp.models.validate_image_size], verbose_name='Фото продукта')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Вес')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Склад')),
                ('animal_type', models.ManyToManyField(related_name='products', to='petapp.animal_type', verbose_name='Тип животного')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.basket', verbose_name='Корзина пользователя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Корзина продуктов',
                'verbose_name_plural': 'Корзины продуктов',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.basket', verbose_name='Корзина')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.orderdetail', verbose_name='Номер заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'История покупки',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('purchase_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petapp.purchasehistory', verbose_name='История покупок')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинги',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
    ]
